// --- 繁體中文 ---
const LANG_ZH_TW = {
    lang: '繁體中文', locale: 'zh-TW',
    settings: '設定', back: '返回', settingsDesc: '自訂你的質感時鐘',
    appearance: '外觀風格', fonts: '顯示字體', importFont: '匯入字體',
    worldClock: '世界時鐘設定', searchCity: '搜尋城市或時區...',
    general: '一般設定', showMillis: '顯示毫秒', legal: '法律與權利',
    privacy: '隱私權條款', terms: '服務條款', cookies: 'Cookie 條款', disclaimer: '免責聲明',
    language: '語言設定', addEditZones: '新增 / 編輯時區',
    work: '專注', break: '短暫休息', long: '長時間休息',
    lap: '計次', agree: '開始探索',
    splashTitle: 'omistry', splashDesc: '專屬於你的質感時光體驗。',
    splashTerms: '繼續使用即表示您同意我們的使用條款。',
    splashBottom: 'Pure Experience · Local Privacy',
    bgGradient: '背景漸層色', textAccent: '文字 / 強調色', bgImage: '背景圖片',
    uploadImage: '上傳圖片', remove: '移除',
    color1: '色彩1', color2: '色彩2', color3: '色彩3', text: '文字', accent: '強調',
    custom: '自訂', imported: '已匯入字體',
    calendar: '月曆', multiTimer: '多計時器',
    addTimer: '新增計時器', noTimers: '點擊 + 新增計時器',
    mon: '一', tue: '二', wed: '三', thu: '四', fri: '五', sat: '六', sun: '日',
    today: '今天', sunrise: '日出', sunset: '日落',
    memento: '生命日曆', birthDate: '您的出生日期', livedWeeks: '已度過的週數', totalWeeks: '總週數 (約 80 年)',
    miniMode: '懸浮/迷你模式', exitMiniMode: '退出迷你模式',
    tabTimer: '計時器', tabPomodoro: '番茄鐘', tabStopwatch: '碼表', tabMonthly: '月曆視圖', tabEvents: '事件與倒數', tabLife: '生命日曆',
    months: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    anniversary: '倒數日', addEvent: '新增事件', eventName: '事件名稱', date: '日期',
    weather: '天氣', temp: '溫度', shareTheme: '分享主題', export: '匯出', import: '導入',
    importPrompt: '請貼上主題代碼', screenSaver: '螢幕保護', ssHint: '移動滑鼠結束',
    daysLeft: '天', daysAgo: '天前',
    fullscreenError: '全螢幕切換失敗', fontLoadError: '字體載入失敗', imageSizeError: '圖片不能超過 5MB',
    invalidThemeCode: '主題代碼錯誤',
    themeModern: '極夜黑', themeLight: '光學白', themeCyber: '霓虹紫', themeForest: '水晶綠', themeCustom: '自訂',
    fontModern: '現代', fontElegant: '經典', fontTechnical: '工程', fontCyber: '未來', fontMirai: '未來圓', fontLine: 'LINE 官方', fontCustom: '已匯入',
    alarmSound: '計時鈴聲', notifications: '系統通知', soundNone: '無', soundBeep: '嗶嗶聲', soundDigital: '電子錶', soundBell: '清脆鈴聲', testSound: '測試鈴聲',
    showProgressRing: '動態進度環', enableMiniTask: '微型任務管理', enableFocusAnalytics: '專注數據統計', enableMeetingPlanner: '智慧時區規劃器', focusGoal: '當前專注目標', focusStats: '專注時長統計', exportImage: '輸出為主題照片', exporting: '正在生成...',
    ringPosition: '進度環位置', ringLeft: '數字左側', ringRight: '數字右側', ringBackground: '背景置中',
    autoZenMode: '計時自動進入專注模式',
    downloadApp: '下載 Android 原生版', downloadingApp: '正在取得下載連結...', appDesc: '安裝 APK 以獲得更流暢的效能與震動回饋',
    updateTitle: '更新與版本', currentVersion: '目前版本', checkUpdate: '檢查更新', checking: '檢查中...', upToDate: '已是最新版本！', newVersion: '有新版本', updateNow: '立即更新', updateDesc: '確保您的 Clockomistry 始終保持最新狀態',
    clearData: '清除所有資料', clearDataDesc: '將刪除本機所有設定、檔案記錄和快取。此操作無法復原。', clearDataConfirm: '確認刪除所有資料？', clearDataDone: '資料已清除，即將重新載入…', clearDataBtn: '清除資料',
    "Taipei": "台北", "Tokyo": "東京", "Seoul": "首爾", "Shanghai": "上海", "Hong Kong": "香港",
    "Singapore": "新加坡", "Bangkok": "曼谷", "Dubai": "杜拜", "Kolkata": "加爾各答", "Ho Chi Minh": "胡志明市",
    "London": "倫敦", "Paris": "巴黎", "Berlin": "柏林", "Rome": "羅馬", "Madrid": "馬德裡", "Moscow": "莫斯科",
    "Amsterdam": "阿姆斯特丹", "Zurich": "蘇黎世", "New York": "紐約", "Los Angeles": "洛杉磯",
    "Chicago": "芝加哥", "Toronto": "多倫多", "Vancouver": "溫哥華", "São Paulo": "聖保羅",
    "Mexico City": "墨西哥城", "Sydney": "雪梨", "Melbourne": "墨爾本", "Auckland": "奧克蘭",
    "Cairo": "開羅", "Johannesburg": "約翰尼斯堡",
    about: '關於本程式', system: '系統', features: '進階功能',
    cancel: '取消', add: '新增', clickToEdit: '點擊以編輯',
    clockLayoutTitle: '時鐘版面樣式',
    layout_classic: '經典橫排', layout_stacked: '堆疊式', layout_minimal: '極簡風', layout_split: '左右分離', layout_digital: '數位儀表',
    use12Hour: '12 / 24 小時制切換', hourlyChime: '整點報時提示音', showSeconds: '顯示秒數', showDate: '顯示日期', showNextEvent: '顯示下一個事件倒數',
    dashboardMode: '一體化儀表板模式', autoDarkMode: '自動深夜模式 (18:00 - 06:00)', enableEcoMode: '省電節能模式 (背景自動降流)',
    particles: '背景粒子特效', tabSequence: '序列計時器', localBackup: '區域備份 (JSON)',
    readyToStart: '準備就緒', emptySequence: '尚未設定序列任務',
    meetingGood: '商務時間 (適合聯繫)', meetingAcceptable: '邊緣時間 (非工作時段)', meetingUnsuitable: '深夜時段 (休息中)',
    hourlyChimeTitle: '整點報時', eventToday: '就在今天！'
};
