// --- English ---
const LANG_EN = {
    lang: 'English', locale: 'en-US',
    settings: 'Settings', back: 'Back', settingsDesc: 'Customize your premium clock',
    appearance: 'Appearance', fonts: 'Fonts', importFont: 'Import Font',
    worldClock: 'World Clock', searchCity: 'Search city or timezone...',
    general: 'General', showMillis: 'Show Milliseconds', legal: 'Legal',
    privacy: 'Privacy Policy', terms: 'Terms of Service', cookies: 'Cookie Policy', disclaimer: 'Disclaimer',
    language: 'Language', addEditZones: 'Add / Edit Zones',
    work: 'Work', break: 'Break', long: 'Long Break',
    lap: 'Lap', agree: 'Get Started',
    splashTitle: 'omistry', splashDesc: 'Your premium time experience.',
    splashTerms: 'By continuing, you agree to our terms of use.',
    splashBottom: 'Pure Experience · Local Privacy',
    bgGradient: 'Background Gradient', textAccent: 'Text / Accent', bgImage: 'Background Image',
    uploadImage: 'Upload Image', remove: 'Remove',
    color1: 'Color 1', color2: 'Color 2', color3: 'Color 3', text: 'Text', accent: 'Accent',
    custom: 'Custom', imported: 'Imported Font',
    calendar: 'Calendar', multiTimer: 'Multi Timer',
    addTimer: 'Add Timer', noTimers: 'Tap + to add a timer',
    mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun',
    today: 'Today', sunrise: 'Sunrise', sunset: 'Sunset',
    memento: 'Life Calendar', birthDate: 'Your Birth Date', livedWeeks: 'Weeks Lived', totalWeeks: 'Total Weeks (~80 yrs)',
    miniMode: 'PIP / Mini Mode', exitMiniMode: 'Exit Mini Mode',
    tabTimer: 'Timer', tabPomodoro: 'Pomodoro', tabStopwatch: 'Stopwatch', tabMonthly: 'Monthly UI', tabEvents: 'Events', tabLife: 'Life Grid',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    anniversary: 'Anniversary', addEvent: 'Add Event', eventName: 'Event Name', date: 'Date',
    weather: 'Weather', temp: 'Temp', shareTheme: 'Share Theme', export: 'Export', import: 'Import',
    importPrompt: 'Paste theme code here', screenSaver: 'Screen Saver', ssHint: 'Move mouse to exit',
    daysLeft: 'days left', daysAgo: 'days ago',
    fullscreenError: 'Fullscreen Change Failed', fontLoadError: 'Font Load Failed', imageSizeError: 'Image too large (>5MB)',
    invalidThemeCode: 'Invalid Theme Code',
    themeModern: 'Midnight', themeLight: 'Optical', themeCyber: 'Cyber', themeForest: 'Crystal', themeCustom: 'Custom',
    fontModern: 'Modern', fontElegant: 'Elegant', fontTechnical: 'Tech', fontCyber: 'Future', fontMirai: 'Mirai Round', fontLine: 'LINE Official', fontCustom: 'Imported',
    alarmSound: 'Alarm Sound', notifications: 'Notifications', soundNone: 'None', soundBeep: 'Beep', soundDigital: 'Digital', soundBell: 'Bell', testSound: 'Test Sound',
    about: 'About App', system: 'System', features: 'Features',
    cancel: 'Cancel', add: 'Add', clickToEdit: 'Click to edit',
    clockLayoutTitle: 'Clock Layout',
    layout_classic: 'Classic', layout_stacked: 'Stacked', layout_minimal: 'Minimal', layout_split: 'Split', layout_digital: 'Digital',
    showProgressRing: 'Progress Ring', enableMiniTask: 'Mini Task List', enableFocusAnalytics: 'Focus Analytics', enableMeetingPlanner: 'Meeting Planner', focusGoal: 'Current Goal', focusStats: 'Focus Stats', exportImage: 'Export as Image', exporting: 'Exporting...',
    ringPosition: 'Ring Position', ringLeft: 'Left of Number', ringRight: 'Right of Number', ringBackground: 'Background Centered',
    autoZenMode: 'Auto Zen Mode on Start',
    downloadApp: 'Download Android App', downloadingApp: 'Fetching link...', appDesc: 'Install the native APK for smoother performance and haptics',
    updateTitle: 'Updates & Version', currentVersion: 'Current Version', checkUpdate: 'Check for Updates', checking: 'Checking...', upToDate: 'You are up to date!', newVersion: 'New version available', updateNow: 'Update Now', updateDesc: 'Keep your Clockomistry always up to date',
    clearData: 'Clear All Data', clearDataDesc: 'Deletes all settings, records and cache on this device. This cannot be undone.', clearDataConfirm: 'Delete all data?', clearDataDone: 'Data cleared, reloading…', clearDataBtn: 'Clear Data',
    "Taipei": "Taipei", "Tokyo": "Tokyo", "Seoul": "Seoul", "Shanghai": "Shanghai", "Hong Kong": "Hong Kong",
    "Singapore": "Singapore", "Bangkok": "Bangkok", "Dubai": "Dubai", "Kolkata": "Kolkata", "Ho Chi Minh": "Ho Chi Minh",
    "London": "London", "Paris": "Paris", "Berlin": "Berlin", "Rome": "Rome", "Madrid": "Madrid", "Moscow": "Moscow",
    "Amsterdam": "Amsterdam", "Zurich": "Zurich", "New York": "New York", "Los Angeles": "Los Angeles",
    "Chicago": "Chicago", "Toronto": "Toronto", "Vancouver": "Vancouver", "São Paulo": "São Paulo",
    "Mexico City": "Mexico City", "Sydney": "Sydney", "Melbourne": "Melbourne", "Auckland": "Auckland",
    "Cairo": "Cairo", "Johannesburg": "Johannesburg",
    use12Hour: '12/24 Hour Format', hourlyChime: 'Hourly Chime', showSeconds: 'Show Seconds', showDate: 'Show Date', showNextEvent: 'Event Countdown',
    dashboardMode: 'Dashboard Mode', autoDarkMode: 'Auto Dark Mode (18:00 - 06:00)', enableEcoMode: 'Eco Mode (Background Battery Saver)',
    particles: 'Particle Backgrounds', tabSequence: 'Timer Sequence', localBackup: 'Local Backup (JSON)',
    readyToStart: 'Ready to Start', emptySequence: 'Empty Sequence List',
    meetingGood: 'Business Hours (Good)', meetingAcceptable: 'Outside Hours (Acceptable)', meetingUnsuitable: 'Sleeping Hours (Unsuitable)',
    hourlyChimeTitle: 'Hourly Chime', eventToday: 'Today!'
};
