// --- 日本語 ---
const LANG_JA = {
    lang: '日本語', locale: 'ja-JP',
    settings: '設定', back: '戻る', settingsDesc: 'プレミアム時計をカスタマイズ',
    appearance: '外観', fonts: 'フォント', importFont: 'フォントを読込',
    worldClock: '世界時計', searchCity: '都市またはタイムゾーンを検索...',
    general: '一般', showMillis: 'ミリ秒を表示', legal: '法的情報',
    privacy: 'プライバシー', terms: '利用規規約', cookies: 'Cookie', disclaimer: '免責事項',
    language: '言語', addEditZones: 'ゾーンを追加 / 編輯',
    work: '作業', break: '休憩', long: '長時間休憩',
    lap: 'ラップ', agree: '始める',
    splashTitle: 'omistry', splashDesc: 'あなただけの上質な時間體驗。',
    splashTerms: '続行することで利用規約に同意したものとみなされます。',
    splashBottom: 'Pure Experience · Local Privacy',
    bgGradient: '背景グラデーション', textAccent: 'テキスト / アクセント', bgImage: '背景画像',
    uploadImage: '画像をアップ', remove: '削除',
    color1: '色1', color2: '色2', color3: '色3', text: 'テキスト', accent: 'アクセント',
    custom: 'カスタム', imported: '読込済みフォント',
    calendar: 'カレンダー', multiTimer: 'マルチタイマー',
    addTimer: 'タイマーを追加', noTimers: '+ でタイマーを追加',
    mon: '月', tue: '火', wed: '水', thu: '木', fri: '金', sat: '土', sun: '日',
    today: '今日', sunrise: '日の出', sunset: '日の入り',
    memento: 'ライフカレンダー', birthDate: 'あなたの生年月日', livedWeeks: '過ごした週', totalWeeks: '合計 (約80年)',
    miniMode: 'ミニモード', exitMiniMode: 'ミニモードを終了',
    tabTimer: 'タイマー', tabPomodoro: 'ポモドーロ', tabStopwatch: 'ストップウォッチ', tabMonthly: '月カレンダー', tabEvents: '記念日', tabLife: '人生',
    months: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    anniversary: 'お祝い', addEvent: 'イベント追加', eventName: '名目', date: '日付',
    weather: '天氣', temp: '溫度', shareTheme: 'テーマ共有', export: '書き出し', import: '読み込み',
    importPrompt: 'コードを貼り付け', screenSaver: 'スクリーンセーバー', ssHint: 'マウスを動かして終了',
    daysLeft: '日', daysAgo: '日前',
    fullscreenError: '全畫面切換失敗', fontLoadError: 'フォント読込失敗', imageSizeError: '畫像は 5MB 未満である必要があります',
    invalidThemeCode: 'テーマコードが無効です',
    themeModern: '真夜中', themeLight: 'ライト', themeCyber: 'サイバー', themeForest: 'フォレスト', themeCustom: 'カスタム',
    fontModern: 'モダン', fontElegant: 'エレガント', fontTechnical: 'テック', fontCyber: 'フューチャー', fontMirai: '未来円', fontLine: 'LINE 公式', fontCustom: 'カスタム',
    alarmSound: 'アラーム音', notifications: '通知', soundNone: '無し', soundBeep: 'ビープ', soundDigital: 'デジタル', soundBell: 'ベル', testSound: 'テスト音',
    showProgressRing: 'プログレスリング', enableMiniTask: 'ミニタスク管理', enableFocusAnalytics: '集中時間統計', enableMeetingPlanner: 'MTGプランナー', focusGoal: '現在の目標', focusStats: '集中時間統計', exportImage: '画像として書き出し', exporting: '書き出し中...',
    ringPosition: 'リングの位置', ringLeft: '数字の左側', ringRight: '数字の右側', ringBackground: '背景の中心',
    autoZenMode: '開始時に集中モード',
    downloadApp: 'Androidアプリをダウンロード', downloadingApp: 'リンクを取得中...', appDesc: 'よりスムーズなパフォーマンスのためにAPKをインストール',
    updateTitle: 'アップデートとバージョン', currentVersion: '現在のバージョン', checkUpdate: 'アップデートを確認', checking: '確認中...', upToDate: '最新版です！', newVersion: '新しいバージョンがあります', updateNow: '今すぐ更新', updateDesc: 'Clockomistryを常に最新の状態に保つ',
    clearData: '全データを削除', clearDataDesc: 'このデバイスのすべての設定、記録、キャッシュを削除します。元に戻せません。', clearDataConfirm: 'すべてのデータを削除しますか？', clearDataDone: 'データを削除しました。再読込み中…', clearDataBtn: 'データを削除',
    "Taipei": "台北", "Tokyo": "東京", "Seoul": "ソウル", "Shanghai": "上海", "Hong Kong": "香港",
    "Singapore": "シンガポール", "Bangkok": "バンコク", "Dubai": "ドバイ", "Kolkata": "コルカタ", "Ho Chi Minh": "ホーチミン",
    "London": "ロンドン", "Paris": "パリ", "Berlin": "ベルリン", "Rome": "ローマ", "Madrid": "マドリード", "Moscow": "モスクワ",
    "Amsterdam": "アムステルダム", "Zurich": "チューリッヒ", "New York": "ニューヨーク", "Los Angeles": "ロサンゼルス",
    "Chicago": "シカゴ", "Toronto": "トロント", "Vancouver": "バンクーバー", "São Paulo": "サンパウロ",
    "Mexico City": "メキシコシティ", "Sydney": "シドニー", "Melbourne": "メルボルン", "Auckland": "オークランド",
    "Cairo": "カイロ", "Johannesburg": "ヨハネスブルグ",
    clockLayoutTitle: '時計レイアウト',
    layout_classic: 'クラシック', layout_stacked: 'スタック', layout_minimal: 'ミニマル', layout_split: 'スプリット', layout_digital: 'デジタル',
    use12Hour: '12/24時間表示', hourlyChime: '毎時チャイム', showSeconds: '秒を表示', showDate: '日付を表示', showNextEvent: '次のイベント',
    dashboardMode: 'ダッシュボードモード', autoDarkMode: '自動深夜モード (18:00 - 06:00)', enableEcoMode: 'エコモード (バッテリー節約)',
    particles: '背景粒子特效', tabSequence: 'シーケンスタイマー', localBackup: 'ローカルバックアップ (JSON)',
    readyToStart: '開始準備完了', emptySequence: 'シーケンスが空です',
    meetingGood: 'ビジネス時間 (連絡可)', meetingAcceptable: '時間外 (許容範囲)', meetingUnsuitable: '深夜帯 (休憩中)',
    hourlyChimeTitle: '毎時チャ與ム', eventToday: '今日です！'
};
