// --- Français ---
const LANG_FR = {
    lang: 'Français', locale: 'fr-FR',
    settings: 'Paramètres', back: 'Retour', settingsDesc: 'Personnalisez votre horloge premium',
    appearance: 'Apparence', fonts: 'Polices', importFont: 'Importer une police',
    worldClock: 'Horloge mondiale', searchCity: 'Rechercher une ville...',
    general: 'Général', showMillis: 'Afficher les millisecondes', legal: 'Mentions légales',
    privacy: 'Confidentialité', terms: 'Conditions d\'utilisation', cookies: 'Cookies', disclaimer: 'Clause de non-responsabilité',
    language: 'Langue', addEditZones: 'Ajouter / Modifier des zones',
    work: 'Travail', break: 'Pause', long: 'Longue pause',
    lap: 'Tour', agree: 'Commencer',
    splashTitle: 'omistry', splashDesc: 'Votre expérience de temps premium.',
    splashTerms: 'En continuant, vous acceptez nos conditions d\'utilisation.',
    splashBottom: 'Expérience Pure · Confidentialité Locale',
    bgGradient: 'Dégradé de fond', textAccent: 'Texte / Accentuation', bgImage: 'Image de fond',
    uploadImage: 'Télécharger une image', remove: 'Supprimer',
    color1: 'Couleur 1', color2: 'Couleur 2', color3: 'Couleur 3', text: 'Texte', accent: 'Accent',
    custom: 'Personnaliser', imported: 'Police importée',
    calendar: 'Calendrier', multiTimer: 'Multi Minuteur',
    addTimer: 'Ajouter un minuteur', noTimers: 'Appuyez sur + pour ajouter',
    mon: 'Lun', tue: 'Mar', wed: 'Mer', thu: 'Jeu', fri: 'Ven', sat: 'Sam', sun: 'Dim',
    today: 'Aujourd\'hui', sunrise: 'Lever du soleil', sunset: 'Coucher du soleil',
    memento: 'Calendrier de vie', birthDate: 'Date de naissance', livedWeeks: 'Semaines vécues', totalWeeks: 'Total (~80 ans)',
    miniMode: 'Mode PIP / Mini', exitMiniMode: 'Quitter le mode mini',
    tabTimer: 'Minuteur', tabPomodoro: 'Pomodoro', tabStopwatch: 'Chronomètre', tabMonthly: 'Vue mensuelle', tabEvents: 'Événements', tabLife: 'Grille de vie',
    months: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    anniversary: 'Anniversaire', addEvent: 'Ajouter un événement', eventName: 'Nom de l\'événement', date: 'Date',
    weather: 'Météo', temp: 'Temp', shareTheme: 'Partager le thème', export: 'Exporter', import: 'Importer',
    importPrompt: 'Collez le code du thème ici', screenSaver: 'Économiseur d\'écran', ssHint: 'Bougez la souris pour sortir',
    daysLeft: 'jours restants', daysAgo: 'jours passés',
    themeModern: 'Minuit', themeLight: 'Optique', themeCyber: 'Cyber', themeForest: 'Cristal', themeCustom: 'Personnalisé',
    fontModern: 'Moderne', fontElegant: 'Élégant', fontTechnical: 'Technique', fontCyber: 'Futur', fontMirai: 'Mirai Round', fontLine: 'LINE Officiel', fontCustom: 'Importé',
    alarmSound: 'Alarme', notifications: 'Notifications', soundNone: 'Aucune', soundBeep: 'Bip', soundDigital: 'Digital', soundBell: 'Cloche', testSound: 'Tester',
    about: 'À propos', system: 'Système', features: 'Fonctionnalités',
    cancel: 'Annuler', add: 'Ajouter', clickToEdit: 'Cliquer pour modifier',
    clockLayoutTitle: 'Mise en page',
    layout_classic: 'Classique', layout_stacked: 'Empilé', layout_minimal: 'Minimal', layout_split: 'Séparé', layout_digital: 'Digital',
    showProgressRing: 'Anneau de progression', autoZenMode: 'Mode Zen automatique',
    particles: 'Particules de fond', tabSequence: 'Séquence du minuteur', localBackup: 'Sauvegarde locale (JSON)',
    readyToStart: 'Prêt à démarrer', emptySequence: 'Liste de séquence vide',
    meetingGood: 'Heures de bureau (Bon)', meetingAcceptable: 'Heures limites (Acceptable)', meetingUnsuitable: 'Heures de sommeil (Inadapté)',
    hourlyChimeTitle: 'Carillon horaire', eventToday: 'C\'est aujourd\'hui !'
};
