// --- Deutsch ---
const LANG_DE = {
    lang: 'Deutsch', locale: 'de-DE',
    settings: 'Einstellungen', back: 'Zurück', settingsDesc: 'Personalisiere deine Premium-Uhr',
    appearance: 'Aussehen', fonts: 'Schriftarten', importFont: 'Schriftart importieren',
    worldClock: 'Weltuhr', searchCity: 'Stadt suchen...',
    general: 'Allgemein', showMillis: 'Millisekunden anzeigen', legal: 'Rechtliches',
    privacy: 'Datenschutz', terms: 'Nutzungsbedingungen', cookies: 'Cookies', disclaimer: 'Haftungsausschluss',
    language: 'Sprache', addEditZones: 'Zonen hinzufügen / bearbeiten',
    work: 'Arbeit', break: 'Pause', long: 'Lange Pause',
    lap: 'Runde', agree: 'Loslegen',
    splashTitle: 'omistry', splashDesc: 'Dein Premium-Zeiterlebnis.',
    splashTerms: 'Durch Fortfahren akzeptierst du unsere Nutzungsbedingungen.',
    splashBottom: 'Pure Erfahrung · Lokaler Datenschutz',
    bgGradient: 'Hintergrundverlauf', textAccent: 'Text / Akzent', bgImage: 'Hintergrundbild',
    uploadImage: 'Bild hochladen', remove: 'Entfernen',
    color1: 'Farbe 1', color2: 'Farbe 2', color3: 'Farbe 3', text: 'Text', accent: 'Akzent',
    custom: 'Benutzerdefiniert', imported: 'Importierte Schrift',
    calendar: 'Kalender', multiTimer: 'Multi-Timer',
    addTimer: 'Timer hinzufügen', noTimers: 'Tippe +, um hinzuzufügen',
    mon: 'Mo', tue: 'Di', wed: 'Mi', thu: 'Do', fri: 'Fr', sat: 'Sa', sun: 'So',
    today: 'Heute', sunrise: 'Sonnenaufgang', sunset: 'Sonnenuntergang',
    memento: 'Lebenskalender', birthDate: 'Geburtsdatum', livedWeeks: 'Gelebte Wochen', totalWeeks: 'Gesamt (~80 J.)',
    miniMode: 'PIP / Mini-Modus', exitMiniMode: 'Mini-Modus verlassen',
    tabTimer: 'Timer', tabPomodoro: 'Pomodoro', tabStopwatch: 'Stoppuhr', tabMonthly: 'Monatsansicht', tabEvents: 'Ereignisse', tabLife: 'Lebensraster',
    months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    anniversary: 'Jahrestag', addEvent: 'Ereignis hinzufügen', eventName: 'Ereignisname', date: 'Datum',
    weather: 'Wetter', temp: 'Temp', shareTheme: 'Thema teilen', export: 'Exportieren', import: 'Importieren',
    importPrompt: 'Themencode hier einfügen', screenSaver: 'Bildschirmschoner', ssHint: 'Maus bewegen zum Beenden',
    daysLeft: 'Tage übrig', daysAgo: 'Tage her',
    themeModern: 'Mitternacht', themeLight: 'Optisch', themeCyber: 'Cyber', themeForest: 'Kristall', themeCustom: 'Benutzerdefiniert',
    fontModern: 'Modern', fontElegant: 'Elegant', fontTechnical: 'Technisch', fontCyber: 'Zukunft', fontMirai: 'Mirai Round', fontLine: 'LINE Offiziell', fontCustom: 'Importiert',
    alarmSound: 'Alarmton', notifications: 'Benachrichtigungen', soundNone: 'Keiner', soundBeep: 'Piep', soundDigital: 'Digital', soundBell: 'Glocke', testSound: 'Testen',
    about: 'Über die App', system: 'System', features: 'Funktionen',
    cancel: 'Abbrechen', add: 'Hinzufügen', clickToEdit: 'Zum Bearbeiten klicken',
    clockLayoutTitle: 'Layout',
    layout_classic: 'Klassisch', layout_stacked: 'Gstapelt', layout_minimal: 'Minimal', layout_split: 'Geteilt', layout_digital: 'Digital',
    showProgressRing: 'Fortschrittsring', autoZenMode: 'Automatischer Zen-Modus',
    particles: 'Hintergrundpartikel', tabSequence: 'Timer-Sequenz', localBackup: 'Lokales Backup (JSON)',
    readyToStart: 'Bereit zum Start', emptySequence: 'Sequenzliste leer',
    meetingGood: 'Bürozeiten (Gut)', meetingAcceptable: 'Grenzzeit (Akzeptabel)', meetingUnsuitable: 'Schlafenszeit (Ungeeignet)',
    hourlyChimeTitle: 'Stundensignal', eventToday: 'Heute ist es soweit!'
};
