// --- Русский ---
const LANG_RU = {
    lang: 'Русский', locale: 'ru-RU',
    settings: 'Настройки', back: 'Назад', settingsDesc: 'Настройте свои премиальные часы',
    appearance: 'Внешний вид', fonts: 'Шрифты', importFont: 'Импорт шрифта',
    worldClock: 'Мировое время', searchCity: 'Поиск города...',
    general: 'Общие', showMillis: 'Миллисекунды', legal: 'Юридические данные',
    privacy: 'Конфиденциальность', terms: 'Условия использования', cookies: 'Cookies', disclaimer: 'Отказ от ответственности',
    language: 'Язык', addEditZones: 'Добавить / Изменить зоны',
    work: 'Работа', break: 'Перерыв', long: 'Длинный перерыв',
    lap: 'Круг', agree: 'Начать',
    splashTitle: 'omistry', splashDesc: 'Ваш премиальный опыт времени.',
    splashTerms: 'Продолжая, вы соглашаетесь с условиями использования.',
    splashBottom: 'Чистый опыт · Локальная приватность',
    bgGradient: 'Градиент фона', textAccent: 'Текст / Акцент', bgImage: 'Фоновое изображение',
    uploadImage: 'Загрузить изображение', remove: 'Удалить',
    color1: 'Цвет 1', color2: 'Цвет 2', color3: 'Цвет 3', text: 'Текст', accent: 'Акцент',
    custom: 'Пользовательский', imported: 'Импортированный шрифт',
    calendar: 'Календарь', multiTimer: 'Мульти-таймер',
    addTimer: 'Добавить таймер', noTimers: 'Нажмите +, чтобы добавить',
    mon: 'Пн', tue: 'Вт', wed: 'Ср', thu: 'Чт', fri: 'Пт', sat: 'Сб', sun: 'Вс',
    today: 'Сегодня', sunrise: 'Восход', sunset: 'Закат',
    memento: 'Календарь жизни', birthDate: 'Дата рождения', livedWeeks: 'Прожито недель', totalWeeks: 'Всего (~80 лет)',
    miniMode: 'Мини-режим', exitMiniMode: 'Выйти из мини-режима',
    tabTimer: 'Таймер', tabPomodoro: 'Помодоро', tabStopwatch: 'Секундомер', tabMonthly: 'Месяц', tabEvents: 'События', tabLife: 'Жизнь',
    months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    anniversary: 'Событие', addEvent: 'Добавить событие', eventName: 'Название', date: 'Дата',
    weather: 'Погода', temp: 'Темп', shareTheme: 'Поделиться темой', export: 'Экспорт', import: 'Импорт',
    importPrompt: 'Вставьте код темы', screenSaver: 'Заставка', ssHint: 'Двигайте мышь для выхода',
    daysLeft: 'дней осталось', daysAgo: 'дней назад',
    themeModern: 'Полночь', themeLight: 'Оптический', themeCyber: 'Кибер', themeForest: 'Кристалл', themeCustom: 'Свой',
    fontModern: 'Модерн', fontElegant: 'Элегантный', fontTechnical: 'Техно', fontCyber: 'Будущее', fontMirai: 'Mirai Round', fontLine: 'LINE Official', fontCustom: 'Импорт',
    alarmSound: 'Звук будильника', notifications: 'Уведомления', soundNone: 'Нет', soundBeep: 'Бип', soundDigital: 'Цифровой', soundBell: 'Колокольчик', testSound: 'Тест',
    about: 'О приложении', system: 'Система', features: 'Функции',
    cancel: 'Отмена', add: 'Добавить', clickToEdit: 'Нажмите для правки',
    clockLayoutTitle: 'Макет',
    layout_classic: 'Классика', layout_stacked: 'Стек', layout_minimal: 'Минимал', layout_split: 'Сплит', layout_digital: 'Цифровой',
    showProgressRing: 'Кольцо прогресса', autoZenMode: 'Авто-дзен',
    particles: 'Частицы фона', tabSequence: 'Последовательность', localBackup: 'Локальный бэкап (JSON)',
    readyToStart: 'Готово к старту', emptySequence: 'Список пуст',
    meetingGood: 'Рабочее время (ОК)', meetingAcceptable: 'Внеурочно (Приемлемо)', meetingUnsuitable: 'Сон (Не подходит)',
    hourlyChimeTitle: 'Почасовой сигнал', eventToday: 'Сегодня!'
};
