// --- Español ---
const LANG_ES = {
    lang: 'Español', locale: 'es-ES',
    settings: 'Ajustes', back: 'Volver', settingsDesc: 'Personaliza tu reloj premium',
    appearance: 'Apariencia', fonts: 'Fuentes', importFont: 'Importar fuente',
    worldClock: 'Reloj mundial', searchCity: 'Buscar ciudad...',
    general: 'General', showMillis: 'Mostrar milisegundos', legal: 'Legal',
    privacy: 'Privacidad', terms: 'Términos', cookies: 'Cookies', disclaimer: 'Aviso legal',
    language: 'Idioma', addEditZones: 'Añadir / Editar zonas',
    work: 'Trabajo', break: 'Descanso', long: 'Descanso largo',
    lap: 'Vuelta', agree: 'Empezar',
    splashTitle: 'omistry', splashDesc: 'Tu experiencia de tiempo premium.',
    splashTerms: 'Al continuar, aceptas nuestros términos de uso.',
    splashBottom: 'Experiencia Pura · Privacidad Local',
    bgGradient: 'Degradado de fondo', textAccent: 'Texto / Acento', bgImage: 'Imagen de fondo',
    uploadImage: 'Subir imagen', remove: 'Eliminar',
    color1: 'Color 1', color2: 'Color 2', color3: 'Color 3', text: 'Texto', accent: 'Acento',
    custom: 'Personalizado', imported: 'Fuente importada',
    calendar: 'Calendario', multiTimer: 'Multi Temporizador',
    addTimer: 'Añadir temporizador', noTimers: 'Pulsa + para añadir',
    mon: 'Lun', tue: 'Mar', wed: 'Mié', thu: 'Jue', fri: 'Vie', sat: 'Sáb', sun: 'Dom',
    today: 'Hoy', sunrise: 'Amanecer', sunset: 'Atardecer',
    memento: 'Calendario de vida', birthDate: 'Fecha de nacimiento', livedWeeks: 'Semanas vividas', totalWeeks: 'Total (~80 años)',
    miniMode: 'Modo PIP / Mini', exitMiniMode: 'Salir del modo mini',
    tabTimer: 'Temporizador', tabPomodoro: 'Pomodoro', tabStopwatch: 'Cronómetro', tabMonthly: 'Vista mensual', tabEvents: 'Eventos', tabLife: 'Vida',
    months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    anniversary: 'Aniversario', addEvent: 'Añadir evento', eventName: 'Nombre', date: 'Fecha',
    weather: 'Clima', temp: 'Temp', shareTheme: 'Compartir tema', export: 'Exportar', import: 'Importar',
    importPrompt: 'Pega el código del tema', screenSaver: 'Salvapantallas', ssHint: 'Mueve el ratón para salir',
    daysLeft: 'días restantes', daysAgo: 'días atrás',
    themeModern: 'Medianoche', themeLight: 'Óptico', themeCyber: 'Cyber', themeForest: 'Cristal', themeCustom: 'Personalizado',
    fontModern: 'Moderno', fontElegant: 'Elegante', fontTechnical: 'Técnico', fontCyber: 'Futuro', fontMirai: 'Mirai Round', fontLine: 'LINE Official', fontCustom: 'Importada',
    alarmSound: 'Sonido de alarma', notifications: 'Notificaciones', soundNone: 'Ninguno', soundBeep: 'Bip', soundDigital: 'Digital', soundBell: 'Campana', testSound: 'Probar',
    about: 'Acerca de', system: 'Sistema', features: 'Funciones',
    cancel: 'Cancelar', add: 'Añadir', clickToEdit: 'Clic para editar',
    clockLayoutTitle: 'Diseño',
    layout_classic: 'Clásico', layout_stacked: 'Apilado', layout_minimal: 'Minimalista', layout_split: 'Dividido', layout_digital: 'Digital',
    showProgressRing: 'Anillo de progreso', autoZenMode: 'Modo Zen automático',
    particles: 'Partículas de fondo', tabSequence: 'Secuencia', localBackup: 'Respaldo local (JSON)',
    readyToStart: 'Listo para empezar', emptySequence: 'Lista vacía',
    meetingGood: 'Horario laboral (Bien)', meetingAcceptable: 'Fuera de horario (Aceptable)', meetingUnsuitable: 'Horario de sueño (In adecuado)',
    hourlyChimeTitle: 'Campanada horaria', eventToday: '¡Es hoy!'
};
