// --- Lingua Latina ---
const LANG_LA = {
    lang: 'Latina', locale: 'la-LA',
    settings: 'Configurationes', back: 'Retro', settingsDesc: 'Personaliza horologium tuum',
    appearance: 'Apparentia', fonts: 'Frontes', importFont: 'Importa frontem',
    worldClock: 'Horologium Mundi', searchCity: 'Quaere urbem...',
    general: 'Generalis', showMillis: 'Ostende millesimas', legal: 'Iuridica',
    privacy: 'Privatum', terms: 'Termini', cookies: 'Crustula', disclaimer: 'Exoneratio',
    language: 'Lingua', addEditZones: 'Adde / Edita zonas',
    work: 'Labor', break: 'Quies', long: 'Quies longa',
    lap: 'Lapsus', agree: 'Incipe',
    splashTitle: 'omistry', splashDesc: 'Experientia temporis premium.',
    splashTerms: 'Continuando, terminos nostros accipis.',
    splashBottom: 'Experientia Pura · Privatum Locale',
    bgGradient: 'Gradus coloris', textAccent: 'Contextus / Accentus', bgImage: 'Imago fundi',
    uploadImage: 'Enere imaginem', remove: 'Remove',
    color1: 'Color I', color2: 'Color II', color3: 'Color III', text: 'Contextus', accent: 'Accentus',
    custom: 'Proprium', imported: 'Frons importata',
    calendar: 'Calendarium', multiTimer: 'Multi-Temporarium',
    addTimer: 'Adde temporarium', noTimers: 'Preme + ut addas',
    mon: 'Lun', tue: 'Mar', wed: 'Mer', thu: 'Iov', fri: 'Ven', sat: 'Sat', sun: 'Sol',
    today: 'Hodie', sunrise: 'Ortus solis', sunset: 'Occasus solis',
    memento: 'Calendarium Vitae', birthDate: 'Dies natalis tuus', livedWeeks: 'Septimanae peractae', totalWeeks: 'Summa (~80 anni)',
    miniMode: 'Modus Parvus', exitMiniMode: 'Exi modo parvo',
    tabTimer: 'Temporarium', tabPomodoro: 'Pomodoro', tabStopwatch: 'Horoscopus', tabMonthly: 'Mensis', tabEvents: 'Eventus', tabLife: 'Vita',
    months: ['Ianuarius', 'Februarius', 'Martius', 'Aprilis', 'Maius', 'Iunius', 'Iulius', 'Augustus', 'September', 'October', 'November', 'December'],
    anniversary: 'Anniversarium', addEvent: 'Adde eventum', eventName: 'Nomen', date: 'Dies',
    weather: 'Caeli status', temp: 'Temp', shareTheme: 'Partire thema', export: 'Exporta', import: 'Importa',
    importPrompt: 'Scribe codicem thematis', screenSaver: 'Servator scrinii', ssHint: 'Move murem ut exeas',
    daysLeft: 'dies relicti', daysAgo: 'dies abhinc',
    themeModern: 'Media Nox', themeLight: 'Opticus', themeCyber: 'Cyber', themeForest: 'Crystallum', themeCustom: 'Proprium',
    fontModern: 'Modernus', fontElegant: 'Elegans', fontTechnical: 'Technicus', fontCyber: 'Futurus', fontMirai: 'Mirai Round', fontLine: 'LINE Officialis', fontCustom: 'Importatus',
    alarmSound: 'Sonus signi', notifications: 'Notitiae', soundNone: 'Nullus', soundBeep: 'Pipitus', soundDigital: 'Digitalis', soundBell: 'Tintinnabulum', testSound: 'Proba',
    about: 'De hoc', system: 'Systema', features: 'Facultates',
    cancel: 'Cancella', add: 'Adde', clickToEdit: 'Preme ut editas',
    clockLayoutTitle: 'Dispositio',
    layout_classic: 'Classicum', layout_stacked: 'Cumulatum', layout_minimal: 'Minimum', layout_split: 'Divisum', layout_digital: 'Digitale',
    showProgressRing: 'Anulus progressionis', autoZenMode: 'Modus Zen automaticus',
    particles: 'Particulae fundi', tabSequence: 'Sequentia', localBackup: 'Auxilium locale (JSON)',
    readyToStart: 'Paratus', emptySequence: 'Sequentia vacua',
    meetingGood: 'Horae laboris (Bene)', meetingAcceptable: 'Extra horas (Acceptabile)', meetingUnsuitable: 'Horae somni (Non convenit)',
    hourlyChimeTitle: 'Signum horarium', eventToday: 'Hodie est!'
};
